name: semantic-release
on:
  workflow_dispatch:

jobs:
  call_semantic_release:
    permissions:
        id-token: write
        contents: write 
    uses: datajoint/.github/.github/workflows/semantic-release.yaml@main
